INSERT INTO ACCOUNT(FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('Sample', 'User1', 'sample.user1@none.com');

INSERT INTO ACCOUNT(FIRST_NAME, LAST_NAME, EMAIL)
VALUES ('Sample', 'User2', 'sample.user2@none.com');

INSERT INTO WALLET(ACCOUNT_ID, STATUS, CREATION_DATE, BALANCE, BALANCE_AVAILABLE, CURRENCY)
VALUES ((SELECT ID FROM ACCOUNT WHERE EMAIL = 'sample.user1@none.com'),
        'ACTIVE',
        '2019-04-27 22:20:59.123',
        99.99,
        99.99,
        'EUR');

INSERT INTO WALLET(ACCOUNT_ID, STATUS, CREATION_DATE, BALANCE, BALANCE_AVAILABLE, CURRENCY)
VALUES ((SELECT ID FROM ACCOUNT WHERE EMAIL = 'sample.user2@none.com'),
        'ACTIVE',
        '2019-04-27 22:20:59.123',
        199.29,
        199.29,
        'EUR');

INSERT INTO WALLET(ACCOUNT_ID, STATUS, CREATION_DATE, BALANCE, BALANCE_AVAILABLE, CURRENCY)
VALUES ((SELECT ID FROM ACCOUNT WHERE EMAIL = 'sample.user2@none.com'),
        'ACTIVE',
        '2019-04-27 22:20:59.123',
        5.29,
        5.29,
        'USD');

INSERT INTO TRANSACTION_LOG(STATUS, CREATION_DATE, EXECUTION_DATE, AUTHORIZATION_DATE, SENDER_WALLET_ID, RECEIVER_WALLET_ID, AMOUNT,
                            AUTHORIZED_AMOUNT)
VALUES ('CONFIRMED',
        '2019-04-28 13:20:32.005',
        '2019-04-28 13:20:32.005',
        NULL,
        (SELECT WLT.ID
         FROM WALLET WLT
                  JOIN ACCOUNT ACC ON WLT.ACCOUNT_ID = ACC.ID
         WHERE ACC.EMAIL = 'sample.user2@none.com'
           AND WLT.CURRENCY = 'EUR'),
        (SELECT WLT.ID
         FROM WALLET WLT
                  JOIN ACCOUNT ACC ON WLT.ACCOUNT_ID = ACC.ID
         WHERE ACC.EMAIL = 'sample.user1@none.com'
           AND WLT.CURRENCY = 'EUR'),
        50.00,
        NULL);